### ISSUE TITLE
All the broken things

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-data-input-client#128]
# About

This is a running list of bugs in the app. Feel free to add more, assign yourself (add your name near the bug), and create a PR with the fix. 

---

## Test Queue
- [ ] (LOW PRIORITY) queue shows "There are no people in the queue. Search for people above to add them to the queue." when there are people in the queue but the organization has no devices
- [x] queue no work -- Tim (#144)
- [x] search queries that yield no results crashes (unable to process null suggestions) -- Neil (#129)
- [x] search input has react prop name errors -- Neil (#129)
- [x] search results do not display DoB or lookupId (these values may just be blank, and this may not be a bug)- looks like they were just blank and it's not a bug (Alicia)
- [x] adding a patient to the queue does not actually add them to the queue  -- Tim (#142)
- [x] If the same person gets added to the queue twice you can't get either instance out or submit a result for them - **This is currently happening in the demo environment** 
    Notes on this: 1) this should not be possible through the UI, because it's supposed to flag "already in the queue." 2) this should not be possible on the API, because we should have both code and database-level protections against it. I think putting in a bandaid for now and elevating this to a standalone issue for the longer term is the correct approach.  New top-level issue: #151. Bandaid: #152

## Settings
- [ ] Saving settings doesn't save the settings (even with a reload of the app) except for device
- [ ] page errors when required fields are not met
- [ ](Low Priority) device list in form should always have a default device set (first device added is not default)
- [ ] (Low Priority) user should not be able to remove required device
- [ ] (Low Priority) Changing default device sets all devices for tests in the queue to be the default device
- [x] the UI lets you add multiple of the same devices, but the db enforces uniqueness, causing a crash (this bug is unverified) -- Neil (#134)
- [x] internal server error when trying to save settings  -- Tim (#143)
- [x] not possible to add a device to org. might have to do with the default org only having 0 devices -- Neil (#134)

## Add/Edit Patient
- [x] Creating a new patient does not create a new patient (even if you fill out all of the fields)
- [ ] patient.getTestResults() should return a list of `TestEvents`
- [ ] no uniqueness enforcement for lookupId (probably low priority but easy to fix in the DB). should there be? "I think there are duplicates in practice" - Tim
- [ ] A URL http://localhost:3000/organization/123/patient/ without "new" on it infinitely recurses: `http://localhost:3000/organization/123/patient//queue/queue/queue/queue/qu...`
- [ ] (Low priority) after you successfully create a new patient by clicking "Save" the app should redirect you back to People page with the list of people and give you a success message.

- [x] creating a new patient tries to get a patient with id "new" -- Tim (#145)
- [x] add patient mutation breaks query patient api --Tim (https://github.com/CDCgov/prime-data-input-client/commit/727f35f77d4774b5cbce08a0ca80d7bc8095eacd)
- [x] patient.race doesn't save correctly (should be JSONb field in db not String) (**BW** setting aside the implementation details, it's a string in the API schema--is the issue that the client has to serialize and deserialize, or that the data is corrupted somehow?) -- Tim (#155 )
- [x] When you click on a person to edit their profile everything breaks.  (Ben #150)
    ```
    react_devtools_backend.js:2430 TypeError: Cannot read property 'map' of undefined
        at mt (PatientForm.jsx:440)
        at Ho (react-dom.production.min.js:153)
        at vs (react-dom.production.min.js:261)
        at lu (react-dom.production.min.js:246)
        at su (react-dom.production.min.js:246)
        at Zs (react-dom.production.min.js:239)
        at react-dom.production.min.js:123
        at t.unstable_runWithPriority (scheduler.production.min.js:19)
        at Vi (react-dom.production.min.js:122)
        at $i (react-dom.production.min.js:123)
    ```

## Upload patient CSV
- [ ] (LOW PRIORITY) submitting the uploaded csv doesn't do anything

## Results
- [ ] page should display `TestEvent`s not completed TestOrders (**BW:** not clear that the front end should know the difference?)
- [ ] The date displayed for a test result is tomorrow and not today (we can start by hardcoding the timezone to mountain time) (**BW** this is actually a great place for passing arguments to the back end—pass the time zone you want, and let the timestamp be formatted accordingly.  Otherwise, it's gonna be GMT, sorry.)
- [x] add FK to Person and Org to `TestEvent`
- [x] **(High Priority) Results for a test are not displayed on the result page unless you reload the app (seems like the results are not refreshed when a user navigates to the results page)** -- Dave (#153 )

## Misc
- [x] the "reset demo data" button is still hiding in the header
- [ ] (Low Priority) we need an `error.html` error page in the react app
- [ ] (Low Priority) all the urls are old and designed around a RESTful backend. Do we really need complex routing like: `localhost:3000/organization/123/patient`? s
  - might just need  `/queue`, `/results`, `/settings`, `/patients`, and `/user`, and have no url parameters
- [x] client UI seems to get rather badly botched up when it is [deployed to a path other than the server root](https://cdc.simplereport.org/demo/app)
- [x] narrow window pane sizes cause the menu to disappear - Tom (#135)

**Comment by aliciabeckett-gov** [comment]
>submitting the uploaded csv doesn't do anything

That is fine for now and lower priority. We should probably hide the button if anything at this point.

**Comment by benwarfield-usds** [comment]
It seems like error reporting up through the graphql API needs some help--in REST we'd just return a 409 or a 400, not sure what the best way to handle that here is.

**Comment by sharmaneil** [comment]
I think errors are still 200, but the query response has the error object: https://www.apollographql.com/docs/apollo-server/data/errors/

**Comment by benwarfield-usds** [comment]
On the race field, I would think a simple string array would suffice, no?

**Comment by benwarfield-usds** [comment]
And I commented a couple places above about things which look like bugs or issues caused by tight coupling between the DB and API layers: this is exactly what façade (API) models are for, and I would recommend we use them in place of the DB models for those cases.

**Comment by benwarfield-usds** [comment]
I found the way to poke informative errors into the GraphQL response—I will implement it on the one I just added and we can work from there.

**Comment by pete-usds** [comment]
See this note from Katie about bugs she found in the app and compare against what's here: https://github.com/CDCgov/prime-central/issues/122#issuecomment-733101440

**Comment by aliciabeckett-gov** [comment]
Going to close this out and track issues individually. It's gotten out of date...
